### ISSUE TITLE
[Request] GProgressbar

### ISSUE THREAD

**Issue by pizzadox9999** [keinhaar/gwtswing#1]
Hi @keinhaar,

could you develop a progressbar for gwtswing?
It could be a wrapper around the html progress element.

With best regards pizzadox9999

**Comment by keinhaar** [comment]
Hi @pizzadox9999,
yes, that should be possible. 
I will try that next week.

**Comment by pizzadox9999** [comment]
Thank you very much. It would be a great addition if you want to indicate that something is loading.

**Comment by keinhaar** [comment]
Added GProgressBar. 
At the moment the minimum is always zero, but i've never seen a use case, where a other value was needed/used.
I did not use the html progess element, because that does not allow to paint a text on top of the element, but that is present in JProgressBar. Like in JProgressBar, you can avoid painting the text with setStringPainted(boolean).
You can see an example on the demo page http://www.exware.de/gwtswing/demo.html if you click on "Other". There's also a little + Button to move the progress indicator forward.
Let me know if this matches your expectations.

**Comment by pizzadox9999** [comment]
Indeed, thats all I ever wished for =). Thank you.
