### ISSUE TITLE
[Proposal] Make gwtswing platform independent

### ISSUE THREAD

**Issue by pizzadox9999** [keinhaar/gwtswing#2]
Hi @keinhaar,

I would like to propose the idea of making the project platform independent. I personally think that this is a great project. To have the swing library on the web can be a powerfull tool.
Currently it is (sadly) only implemented for the GWT project. But there a some more projects that are trying to achieve similar goals. For instance TeaVM and JSweet. I'm coming from the TeaVM side. I'm not the maintainer or anything from TeaVM. I'm just a user which would like to have swing support. Currently my approach was to emulate GWT but it didn't seemed feasable for the future, if changes would happen to the main gwtswing project.
Furthermore I would like to contribute to the project, but I also would like to be able to use it in TeaVM.
So the proposal is about making the project platform independent and create new branches for each implementation.
I would be happy if I could implement such a system for this project. But I wouldn't say no to a little help.
If any questions rise I would like to answer them. 

Sincerely pizzadox9999

PS: If you dont want please say it and I will stop all activity with the forking thing.

**Comment by keinhaar** [comment]
Hi @pizzadox9999,
i like the idea of having gwtswing available for TeaVM. I already thought about that, but i've never used TeaVM.
To make this happen we would need to replace all GWT specific Element creations and Event handling with new interfaces and an implementation for GWT and one for TeaVM. 
In fact i've started a (currently) private project named **de.exware.gdom** with an implementation **de.exware.gdom.gwt** to replace the GWT specific code some month ago.
So instead of having a branch for each implementation, i would like to use the same, platform independent implementation of GWTSwing on all Platforms, and only extract the platform specific things.
I would need somebody to create a **de.exware.gdom.teavm** implementation.
Still interested?

**Comment by pizzadox9999** [comment]
Hi, 

yeah, it sounds promesing. I am very much interested. For the time being I would tackle the teavm implementation. Let me know where and how I can provide you with help.
One more thing. Would it be possible for the gitignore file to contain build system and ide specific exclusions, so that everyone can use his prefered systems and tools.

**Comment by pizzadox9999** [comment]
Hi
I wanted to ask, how it will go forward from this point on? I would like to step in and help you to make it happen. I'm somewhat dependent on this project.
I would appreaciate a way to help you.

Pizza

**Comment by keinhaar** [comment]
I've been working on it the last days. I realized that there are more dependencies on GWT than i thought. But i think that about 90% is done now. I will publish a branch if the demo works without direct GWT dependency. I expect that to happen in the next 7 days. Just keep a look on the branches. 
It will be nessesary to move some features like the uploadbutton, because of its heavy GWT dependency, but thats anyway not part of the Swing API.

**Comment by pizzadox9999** [comment]
Thank you very much for the status update. I appreaciate it. =)

**Comment by keinhaar** [comment]
Hi @pizzadox9999 ,
you can give it a try now.
you will need the "gplatform" branch of gwtswing, the "gplatform" repo and the "gplatform.teavm" repo.
When implementing, you should start with TeavmGPlatform, TeavmGPElement, TeavmGPStyle followed by the rest.
I think you can ignore TeavmGPCanvasElement, TeavmGPContext2d and TeavmGPStorage for the beginning.
Please let me know if you can get it to work :-)

**Comment by pizzadox9999** [comment]
Hi @keinhaar,
thank you for the nice work. I have some questions =). I think I can wrap my head around your idea. The "gplatform" branch is the independent implementation of gwtswing and I need gplatform to run it. But I do not understand how to supply the "gplatform.teavm" implementation to "jvm". How are you injecting the platform code into the independent gwtswing implementation? For the implementation what can I change in the gplatform.teavm repo so that it stays comapitble with the gplatform repo. For example you return the type GPElement in the TeavmGPDocument class. Can I return TeavmGPElement or would it break stuff? So what code can I introduce to get the implemenation working. Do you just extend the base classes from gwt? Can I make the Teavm classes abstract to implement the HTMLElement interfaces from TeaVM? But all things considered it looks great and should be possible. If some things are not well formulated please feel free to ask what I meant ^^.

**Comment by keinhaar** [comment]
Hi,
for "gplatform.gwt" i'm using an GWT Entry Point to initialize the Platform automatically. 
```
public class ModuleInitializer implements EntryPoint
{
    @Override
    public void onModuleLoad()
    {
        GwtGPlatform.init();
    }
}
```
I don't know if something similar exists in Teavm, but alternatively you can call the init() Method manually in your Application.
```
TeavmGPlatform.init();
```
GWTSwing itself does no longer use any GWT classes directly. It only uses the classes and interfaces from gplatform. It does not even know that there is a GWT or Teavm implementation of the gplatform.
And yes of course, you can and should return the Teavm Version of a class or interface, but you cannot change the return type to be compatible.
Let's have a look on how GwtGPDocument creates an GwtGPImageElement
```
    public GPImageElement createImageElement()
    {
        ImageElement iel = doc.createImageElement();
        GPImageElement imgElement = new GwtGPImageElement(iel);
        return imgElement;
    }
```
It creates an GWT specific ImageElement and wraps that in a GwtGPImageElement. Because GwtGPImageElement implements GPImageElement this is fully compatible with the platform neutral version of GWTSwing (which will soon become the main version).

Here is the GwtGPImageElement
```
public class GwtGPImageElement extends GwtGPElement implements GPImageElement
{
    public GwtGPImageElement(ImageElement el)
    {
        super(el);
    }

    @Override
    public void setSrc(String url)
    {
        ((ImageElement)getElement()).setSrc(url);
    }

    @Override
    public void setWidth(int iconWidth)
    {
        ((ImageElement)getElement()).setWidth(iconWidth);
    }

    @Override
    public void setHeight(int iconHeight)
    {
        ((ImageElement)getElement()).setHeight(iconHeight);
    }
}
```
As you can see, this implementation simply delegates any method to the underlying GWT ImageElement.
As a result, i'm not extending the GWT classes, but i'm wrapping a lot of them.

In the Teavm implementation use the interfaces and base classes from gplatform as often as possible, but if nessesary you can also cast to the Teavm types if nessesary. I've done so in the GwtGPContext2d like this:
```
    public void drawImage(GPImageElement imageElement, double x, double y)
    {
        GwtGPImageElement gpie = (GwtGPImageElement) imageElement;
        context2d.drawImage((ImageElement)gpie.getElement(), x, y);
    }
```
I can cast the imageElement to GwtGPImageElement, because while running with GWT there will never be an other implementation.
If in doubt, look how i did it in gplatform.gwt, or just ask again. I will be happy to help as much as i can.

**Comment by pizzadox9999** [comment]
Hi, Teavm stumbled across a native method without an implementation it is GWindow.clearSelection(). Here does the compilitation process abort. It would be nice if this method would be platform independent in the future.

Beside that Firefox is putting out: 
"XML-Verarbeitungsfehler: nicht wohlgeformt Adresse: http://127.0.0.1/localization/de.exware.gwtswing.properties Zeile Nr. 1, Spalte 8". I don't know if it comes from Teavm or Firefox itself.

pizzadox9999

**Comment by keinhaar** [comment]
You're right, that clearSelection() is from GWT. I'll replace it with an gplatform version (found 3 more occurences).
the properties file is just a simple properties. maybe you're  are handling it as XML? which is not possible. Check your TeavmGPlatform.loadData() method. It should return simply the text of the loaded resource. Another possible reason may be, that the file is not found?

**Comment by pizzadox9999** [comment]
Thanks. I could resolve the second issue by using chrome which didn't gave any errors.

**Comment by keinhaar** [comment]
ok, but it can not really be a firefox problem, because i'm using firefox all the time.

Am 16. Mai 2023 21:41:26 MESZ schrieb pizzadox9999 ***@***.***>:

**Comment by keinhaar** [comment]
moved clearSelection() to GPlatform. I added a dummy to the TeavmGPlatform. Just update your branch.

**Comment by pizzadox9999** [comment]
Hi, in the time between two new questions rose (they were their but...). First, how should I save my progress? Can I do it in the github repo where I cloned it from? Second, would it be possible to extend the .gitignore files to compensate for that teavm is using maven? Because to build a test project I have to convert all projects from to maven projects and when you change somehting in there github wants to stash all changes, which also includes my maven projects.
pizzadox9999

**Comment by keinhaar** [comment]
To contribute, you will need a fork of the project on github. then clone your local repo from there. then make pull requests for your changes.

you can make additions to the .gitignore as needed. if you like, you can add the pom.xml as well.

**Comment by pizzadox9999** [comment]
Hi, I have a question for a logger. Are you using your own one or how do you approach this topic. Can you suggest any?

**Comment by keinhaar** [comment]
I'm using my own one, because i share a lot of code between backend and my gwt apps. Having my own logger interface allows me to use the same logging logic anywhere. Also it is much smaller then other APIs like log4j or slf4j. To be compatible to third party libraries which use other logging APIs, i have wrappers for log4j, slf4j and java logging, that will use my logging system.

You can achieve the same by using apache commons logging as interface (that's what my company does). Same logic.

**Comment by pizzadox9999** [comment]
UPDATE:25.05.2023_22:56
ok I think now I got a full working test application running. Key was I didn't set the size and thought the application would figure the need space out.

UPDATE:25.05.2023_22:44
ok the problem lies somehow in that gwts-GFrame doesn't have any width or height. After putting some width and height it showed me the button and it worked showing me a popup.
Also do you have an example to run for me?

INITIAL:
Ok thanks, I put a little logger together, it is for the native methods that I can log them. 
Next problem on my list is that I think the HTML generates fine (look at the end), but the website is empty.
Maybe you stumbled across such a thing when writing your backend how did you approach such possibility?



this: ```package org.test;

import de.exware.gplatform.internal.Logger;
import de.exware.gplatform.teavm.TeavmGPlatform;
import de.exware.gwtswing.awt.event.GActionEvent;
import de.exware.gwtswing.awt.event.GActionListener;
import de.exware.gwtswing.swing.GButton;
import de.exware.gwtswing.swing.GFrame;

public class Test {
    public static void main(String[] args) {
        Logger.setLogLevel(Logger.LEVEL_NATIVE);
        TeavmGPlatform.init();
        GFrame gFrame = new GFrame();
        GButton gButton = new GButton("push me");
        gButton.addActionListener(new GActionListener() {
            public void actionPerformed(GActionEvent evt) {
                TeavmGPlatform.getInstance().alert("test");
            }
        });
        gFrame.add(gButton);
        gFrame.setVisible(true);
    }
}```

generates this (more or less)(haha funny enough now it renders it in here i'm loosing it man)

`<html><head>
    <title>Main page</title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
    <link href="./de/exware/gwtswing/gwtswing.css" rel="stylesheet">
    <script type="text/javascript" charset="utf-8" src="teavm/classes.js"></script>
  </head>
  <body onload="main()">
	
  
<div style="left: 0px; top: 50px;"></div><div class="gwts-GFrame gwts-GWindow gwts-GComponent" style="visibility: visible;"><div class="gwts-GPWindow-header gwts-GPanel gwts-GComponent" style="width: 0px; height: 24px; left: 0px; top: 0px;"><div class="gwts-GPWindow-header-text gwts-GLabel gwts-GComponent" style="width: 0px; height: 24px; left: 0px; top: 0px;"></div><div class="gwts-GButton gwts-GAbstractButton gwts-GComponent" tabindex="0" style="width: 14px; height: 21px; left: -26px; top: 0px;">✕</div></div><div class="gwts-GPanel gwts-GComponent" style="width: 0px; height: 0px; left: 0px; top: 25px;"></div><div class="gwts-GButton gwts-GAbstractButton gwts-GComponent" tabindex="0">push me</div></div></body></html>`

**Comment by keinhaar** [comment]
Instead of TeavmGPlatform.getInstance(), you could use GPlatform.getInstance() to be even more Platform independant.
I don't see, how you add the GFrame to the HTML Page? I use GUtilities.addToBody(gFrame) for this. How did you do it?
Little note: You are not forced to use a GFrame. You can also add any other GComponent like a GPanel.

I know the size problem. Currently i always use
```
       GUtilities.addToBody(p);
       p.setBounds(0, 0, GPlatform.getWin().getClientWidth(), GPlatform.getWin().getClientHeight());
```
and then i attach a resize handler to the native Window to reset the bounds if the Browser Window changes the size.

**Comment by keinhaar** [comment]
Happy to see, that your work was successful. I merged your changes.
This may be my fallback if the GWT Project dies (but currently the next new version is on it's way...)

**Comment by keinhaar** [comment]
Could you please describe the process of using gwtswing with TeaVM? Just a short howto, like i did in the README.md.
I would like to add that to the README.md for possible new users :-)

**Comment by pizzadox9999** [comment]
> Happy to see, that your work was successful. I merged your changes. This may be my fallback if the GWT Project dies (but currently the next new version is on it's way...)

Thank you. But new features would be build into the gplatform branch and not in the main branch?
One thing that still floats in my head are pluggable look and feels. What is your take on that topic?

**Comment by pizzadox9999** [comment]
Yeah I will write a little how to in the next time but I think it is far from over. Things like GPlatform.getWin().getClientWidth() are returning zero so I have to look into that. Also I want to test it a little more to ensure most of the stuff is working as intendet and not returning just zero. 
Furthermore are your websites hand crafted or did you use any window builder like tool?

**Comment by keinhaar** [comment]
> Thank you. But new features would be build into the gplatform branch and not in the main branch? One thing that still floats in my head are pluggable look and feels. What is your take on that topic?
No, new Features will be added to the main branch. The gplatform branch will be merged into main as soon as i believe it is stable enough.

I don't have plans for a pluggable look and feel. They aren't used very much in Swing and they would make the code much more complicated. Anyway, a lot of the look can be changed by using a custom css file, but there are still some Components, that need their own css classnames to allow more/easier control of their look.

**Comment by keinhaar** [comment]
> Furthermore are your websites hand crafted or did you use any window builder like tool?

Which pages do you mean?

**Comment by pizzadox9999** [comment]
> > Furthermore are your websites hand crafted or did you use any window builder like tool?
> 
> Which pages do you mean?

The sample pages you have set up. The one you can access through the github link: http://www.exware.de/gwtswing/demo.html.

**Comment by keinhaar** [comment]
That pages are a totally quick hack. Nearly all in one file. It's 99% gwtswing, but currently it directly depends on GWT, because it's my demo APP. 
I never use Window Builders, because the handwritten code is easier to read, the fields are named in a logical way, and i'm 95% sure, that i can write most layouts faster then using any drag and drop tool :-)
That said, did you notice the class de.exware.gwtswing.PartitionedPanel? That's the GComponent that i use for nearly any dialog. It's not a Swing Class, but because i use it so many times, i added it here (see Input in the demo). Just define a number of columns in the constructor, and add one component after the other. The lines in the demo are made with PartitionedPanels addSeparator(String) method.

**Comment by keinhaar** [comment]
Something like
```java
PartionionedPanel panel = new PartitionedPanel(2);
panel.addSeparator("Personal Data");
panel.add(new GLabel("Name"));
panel.add(new GTextField(10);
panel.add(new GLabel("Firstname"));
panel.add(new GTextField(10);
panel.add(new GLabel("Street"));
panel.add(new GTextField(10);
```

**Comment by pizzadox9999** [comment]
Hi, now that I try to right the readme/ howto I realised the out of the box experience wouldn't be so great. You need to clone 3 projects, convert them into maven projects and include the required dependecys in your actual project. Maybe there is a way to get it into maven central? That would make it as easy as include the correct dependency. Besides that it should it be, to get it up and running. All in all only the setup differs the rest is the same.

A first readme/howto version could something like that:
To use GWTSwing with teavm you need the contents of the following
repositoris: gplatform.teavm, gwtswing(gPlatform branch) and gplatform.
Then convert them into maven projects and include the gplatform.teavm 
and gwtswing(gPlatform) as dependecys in your project. Then you need to
initial the TeavmGPPlatform class with a static call to the init method.
After that you are good to go and use the G classes of gwtswing.

Thank you for the hint with the partionedPanel. It is a really strong class, making a login form or something like that in seconds.

Oh and can I post about this project int the google group of teavm?

**Comment by keinhaar** [comment]
> Oh and can I post about this project int the google group of teavm?

Added your text to the README.md and merged the gplatform branch into main. So using the gplatform branch is no longer nessesary.

And of course you can post about it. It's open source :-)

I will close this now, because it's initial intention has been achieved.
